import {randomUUID} from 'node:crypto';
import {hashPassword,verifyPassword,createSession,sessionUser,sessionCookie,digest} from './auth.mjs';
import {aiReady,publicModelSettings} from './config.mjs';
import {fileBytes} from './storage.mjs';
import {now} from './database.mjs';
const safeUser=u=>({id:u.id,email:u.email,name:u.name,role:u.role});
class APIError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new APIError(status,message);};
const text=(v,max=200,min=1)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,`请输入 ${min}～${max} 字符的有效内容`);return v.trim();};
const url=v=>{if(!v)return '';try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw 0;return u.href;}catch{fail(400,'来源网址必须是有效的 HTTP/HTTPS 链接');}};
async function body(req){if(!req.headers['content-type']?.startsWith('application/json'))fail(415,'请提交 JSON 内容');let bytes=0,chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>3*1024*1024)fail(413,'请求超过 3MB 限制');chunks.push(chunk);}try{const v=JSON.parse(Buffer.concat(chunks).toString());if(!v||Array.isArray(v)||typeof v!=='object')throw 0;return v;}catch{fail(400,'请求内容不是有效 JSON');}}
export function createAPI(db,worker,config={}){
const attempts=new Map();function rate(req,limit){const key=req.socket.remoteAddress;const t=Date.now();if(attempts.size>10000)for(const [k,v]of attempts)if(v.until<t)attempts.delete(k);const item=attempts.get(key)||{count:0,until:t+600000};if(item.until<t){item.count=0;item.until=t+600000;}item.count++;attempts.set(key,item);if(item.count>limit)fail(429,'请求过于频繁，请稍后重试');}
function own(table,id,user){const row=db.prepare(`SELECT * FROM ${table} WHERE id=? AND user_id=?`).get(id,user.id);if(!row)fail(404,'记录不存在');return row;}
function project(id,user){if(id)own('projects',id,user);return id||null;}
return async(req,res)=>{const send=(status,value,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(value));};try{
const path=new URL(req.url,'http://localhost').pathname;const method=req.method;
if(!['GET','POST'].includes(method))fail(405,'不支持的请求方式');
if(method==='POST'){const origin=req.headers.origin;if(!origin||origin!==`${config.secure?'https':'http'}://${req.headers.host}`)fail(403,'请求来源不匹配');}
if(path==='/api/capabilities'&&method==='GET'){send(200,{account:true,storage:config.storage?.provider||'local_server_sqlite',emailVerified:false,ai:aiReady(config.getAI()),aiProvider:publicModelSettings(config.getAI()).provider,agent:Boolean(config.agentEnabled&&aiReady(config.getAI())),agentEngine:config.agentEnabled?'codex_sdk':null,payment:false,academicSearch:false,maxFileBytes:2*1024*1024});return;}
if(['/api/auth/register','/api/auth/login'].includes(path)&&method==='POST'){
rate(req,30);const b=await body(req);const email=text(b.email,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'邮箱格式不正确');text(b.password,128,10);const password=b.password;let user;
if(path.endsWith('register')){const name=text(b.name,30);if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'该邮箱已注册');user={id:randomUUID(),email,name,role:'user'};const hash=await hashPassword(password);try{db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(user.id,email,name,hash,'user',now());}catch(e){if(e.code?.includes('SQLITE'))fail(409,'该邮箱已注册');throw e;}}
else{const row=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!row){await hashPassword(password);fail(401,'邮箱或密码不正确');}if(!await verifyPassword(password,row.password_hash))fail(401,'邮箱或密码不正确');user=safeUser(row);}
send(200,{user},{'Set-Cookie':sessionCookie(createSession(db,user.id),config.secure)});return;}
const user=sessionUser(db,req);if(!user)fail(401,'请先登录服务账户');
if(path==='/api/auth/me'&&method==='GET'){send(200,{user});return;}
if(path==='/api/auth/logout'&&method==='POST'){const token=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('pk_session='))?.slice(11);if(token)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(digest(token));send(200,{ok:true},{'Set-Cookie':sessionCookie('',config.secure)});return;}
if(path==='/api/projects'){
if(method==='GET'){send(200,{items:db.prepare('SELECT * FROM projects WHERE user_id=? ORDER BY updated_at DESC').all(user.id)});return;}
const b=await body(req);if(db.prepare('SELECT count(*) n FROM projects WHERE user_id=?').get(user.id).n>=1000)fail(409,'项目数量达到本地限制');const id=randomUUID();const t=now();db.prepare('INSERT INTO projects VALUES(?,?,?,?,?,?,?)').run(id,user.id,text(b.title),text(b.degree||'本科',20),text(b.major||'',100,0),t,t);send(201,{item:own('projects',id,user)});return;}
if(path==='/api/files'){
if(method==='GET'){send(200,{items:db.prepare('SELECT id,project_id,name,kind,bytes,sha256,created_at FROM files WHERE user_id=? ORDER BY created_at DESC').all(user.id)});return;}
const b=await body(req),name=text(b.name,200),kind=name.split('.').at(-1).toLowerCase();if(!['txt','docx','pdf'].includes(kind))fail(400,'支持 TXT、DOCX 和文本 PDF');if(typeof b.data!=='string'||!b.data.length||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(b.data))fail(400,'文件编码无效');const buffer=Buffer.from(b.data,'base64');if(!buffer.length||buffer.length>2*1024*1024)fail(413,'文件最大 2MB');const total=db.prepare('SELECT coalesce(sum(bytes),0) n FROM files WHERE user_id=?').get(user.id).n;if(total+buffer.length>50*1024*1024)fail(409,'当前账户文件总量最多 50MB');if(kind==='pdf'&&!buffer.subarray(0,5).equals(Buffer.from('%PDF-')))fail(400,'PDF 文件格式无效');if(kind==='docx'&&!buffer.subarray(0,2).equals(Buffer.from('PK')))fail(400,'DOCX 文件格式无效');const id=randomUUID();const projectId=project(b.projectId,user);let storageKey=null;if(config.storage)storageKey=await config.storage.put(id,user.id,kind,buffer);db.prepare('INSERT INTO files(id,user_id,project_id,name,kind,bytes,sha256,body,created_at,storage_provider,storage_key,storage_bucket) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,user.id,projectId,name,kind,buffer.length,digest(buffer),storageKey?Buffer.alloc(0):buffer,now(),config.storage?.provider||'local_server_sqlite',storageKey,config.storage?.bucket||null);send(201,{id});return;}
const download=path.match(/^\/api\/files\/([^/]+)\/download$/);if(download&&method==='GET'){const file=own('files',download[1],user);const buffer=await fileBytes(file,config.storage);res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="document.${file.kind}"; filename*=UTF-8''${encodeURIComponent(file.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(buffer);return;}
if(path==='/api/jobs'){
if(method==='GET'){send(200,{items:db.prepare('SELECT id,project_id,type,status,stage,error,result_id,attempt,created_at,updated_at FROM jobs WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(user.id)});return;}
const b=await body(req);const type=b.type;if(!['parse','polish','review','compare','agent'].includes(type))fail(400,'不支持的任务');if(['polish','review','agent'].includes(type)&&!aiReady(config.getAI()))fail(503,'AI 服务尚未配置');if(type==='agent'&&!config.agentEnabled)fail(503,'Codex 智能任务未启用');const projectId=project(b.projectId,user);let input;
if(type==='parse'){const file=own('files',b.fileId||'',user);if(projectId&&file.project_id&&projectId!==file.project_id)fail(400,'文件与任务所属项目不一致');input={fileId:file.id};}
else{input={text:(text(b.text,type==='compare'?8000:6000),b.text),requirements:text(b.requirements||'',2000,0)};if(type==='agent'){const ids=b.fileIds??[];if(!Array.isArray(ids)||ids.length>5||ids.some(id=>typeof id!=='string')||new Set(ids).size!==ids.length)fail(400,'请最多选择 5 份不同材料');input.fileIds=ids.map(id=>{const file=own('files',id,user);if(projectId&&file.project_id&&file.project_id!==projectId)fail(400,'材料与任务所属项目不一致');return file.id;});}if(type==='compare'){if(!Array.isArray(b.sources)||!b.sources.length||b.sources.length>5)fail(400,'需要 1～5 份实际对照材料');input.title=text(b.title||'论文正文');input.sources=b.sources.map((s,i)=>({id:`source-${i+1}`,title:text(s.title),text:(text(s.text,8000),s.text),authors:Array.isArray(s.authors)?s.authors.slice(0,10).map(a=>text(a,100)):[],year:s.year?text(String(s.year),4):null,doi:text(s.doi||'',200,0),url:url(s.url),provider:'user_provided',sourceStatus:'unverified_user_material'}));}}
const key=text(b.idempotencyKey,100);const hash=digest(JSON.stringify({type,input,projectId}));const existing=db.prepare('SELECT id,input_hash FROM jobs WHERE user_id=? AND idempotency_key=?').get(user.id,key);if(existing){if(existing.input_hash!==hash)fail(409,'重复请求标识已用于其他内容');send(200,{id:existing.id});return;}if(db.prepare("SELECT count(*) n FROM jobs WHERE user_id=? AND status IN ('queued','running')").get(user.id).n>=3)fail(409,'最多同时提交 3 个待处理任务');const id=randomUUID(),t=now();db.prepare('INSERT INTO jobs(id,user_id,project_id,type,status,stage,input,idempotency_key,input_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,user.id,projectId,type,'queued','queued',JSON.stringify(input),key,hash,t,t);send(201,{id});return;}
const action=path.match(/^\/api\/jobs\/([^/]+)\/(cancel|retry)$/);if(action&&method==='POST'){const job=own('jobs',action[1],user);if(action[2]==='cancel'){if(!['queued','running'].includes(job.status))fail(409,'任务已结束');db.prepare("UPDATE jobs SET status='cancelled',stage='cancelled',updated_at=? WHERE id=?").run(now(),job.id);worker.cancel(job.id);}else{if(job.status!=='failed')fail(409,'仅失败任务可重试');if(db.prepare("SELECT count(*) n FROM jobs WHERE user_id=? AND status IN ('queued','running')").get(user.id).n>=3)fail(409,'等待任务已达到上限');db.prepare("UPDATE jobs SET status='queued',stage='queued',error=NULL,updated_at=? WHERE id=?").run(now(),job.id);}send(200,{ok:true});return;}
if(path==='/api/results'&&method==='GET'){send(200,{items:db.prepare('SELECT id,project_id,job_id,type,title,created_at FROM results WHERE user_id=? ORDER BY created_at DESC LIMIT 500').all(user.id)});return;}
const revision=path.match(/^\/api\/results\/([^/]+)\/revisions$/);if(revision){const result=own('results',revision[1],user);if(method==='GET'){send(200,{items:db.prepare('SELECT id,body,created_at FROM result_revisions WHERE result_id=? AND user_id=? ORDER BY created_at DESC').all(result.id,user.id)});return;}const b=await body(req);const id=randomUUID();db.prepare('INSERT INTO result_revisions VALUES(?,?,?,?,?)').run(id,result.id,user.id,(text(b.text,100000),b.text),now());send(201,{id});return;}
const result=path.match(/^\/api\/results\/([^/]+)$/);if(result&&method==='GET'){const row=own('results',result[1],user);send(200,{item:{...row,body:JSON.parse(row.body)}});return;}
if(path==='/api/usage'&&method==='GET'){send(200,{items:db.prepare('SELECT * FROM usage WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(user.id),billingEnabled:false});return;}
if(path==='/api/products'&&method==='GET'){send(200,{items:db.prepare('SELECT * FROM products').all().map(p=>({...p,rules:JSON.parse(p.rules)})),paymentEnabled:false});return;}
if(path==='/api/orders'){if(method==='POST')fail(503,'价格规则和支付未启用，不能创建购买订单');send(200,{items:db.prepare('SELECT * FROM orders WHERE user_id=?').all(user.id)});return;}
if(path==='/api/feedback'){if(method==='GET'){send(200,{items:db.prepare('SELECT * FROM feedback WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(user.id)});return;}const b=await body(req);if(db.prepare('SELECT count(*) n FROM feedback WHERE user_id=?').get(user.id).n>=100)fail(409,'反馈数量达到限制');const id=randomUUID();db.prepare('INSERT INTO feedback VALUES(?,?,?,?,?)').run(id,user.id,text(b.category||'产品建议',30),text(b.text,3000),now());send(201,{id});return;}
if(path==='/api/admin/model'){
if(user.role!=='admin')fail(403,'需要管理员权限');
if(method==='POST'){const b=await body(req);const model=text(b.model,100);if(!/^[a-zA-Z0-9][a-zA-Z0-9._:/-]*$/.test(model)||typeof b.enabled!=='boolean')fail(400,'模型名称或启停状态无效');config.settings.save(model,b.enabled,user.id);}
send(200,{ai:publicModelSettings(config.getAI()),storage:{provider:config.storage?.provider||'local_server_sqlite',bucket:config.storage?.bucket||null,prefix:config.storage?.prefix||null}});return;}
if(path==='/api/admin'&&method==='GET'){if(user.role!=='admin')fail(403,'需要管理员权限');send(200,{users:db.prepare('SELECT id,email,name,role,created_at FROM users').all(),jobs:db.prepare('SELECT id,user_id,type,status,error,created_at FROM jobs ORDER BY created_at DESC LIMIT 100').all(),feedback:db.prepare('SELECT * FROM feedback ORDER BY created_at DESC LIMIT 100').all(),orders:db.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 100').all()});return;}
fail(404,'接口不存在');
}catch(e){send(e.status||500,{error:e.status?e.message:'服务暂时无法完成请求'});}};
}
