import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
const code=await readFile(new URL('../dist/home-app.js',import.meta.url),'utf8');
async function page(t,user){const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.localStorage.setItem('paperknow-local-profile',JSON.stringify({name:'过期本地昵称'}));w.fetch=async path=>{if(user==='offline')throw new Error('offline');return {ok:path!='/api/auth/me'||!!user,status:user?200:401,json:async()=>path==='/api/auth/me'?{user}:{ai:false}};};w.eval(code);for(let i=0;i<10;i++)await new Promise(r=>setTimeout(r,1));return w.document;}
test('guest homepage ignores local nickname and offers real registration plus local tools',async t=>{const d=await page(t,null);assert.equal(d.querySelector('#account-button').textContent,'登录');assert.equal(d.querySelector('#header-start').getAttribute('href'),'/service.html?auth=register');assert.ok(d.querySelector('a[href="/workspace.html#category/writing"]'));assert.equal(d.querySelectorAll('#status-button').length,1);});
test('authenticated homepage uses actual session and shows admin entry only for administrator',async t=>{const d=await page(t,{name:'管理员<script>',email:'a@example.invalid',role:'admin'});assert.equal(d.querySelector('#header-start').getAttribute('href'),'/service.html');d.querySelector('#account-button').click();assert.ok(d.querySelector('a[href="/service.html?view=admin"]'));assert.equal(d.querySelector('#home-dialog-body script'),null);assert.ok(d.querySelector('#home-dialog-body').textContent.includes('管理员<script>'));});
test('ordinary user cannot see admin link; offline homepage retains usable local links',async t=>{const d=await page(t,{name:'用户',email:'u@example.invalid',role:'user'});d.querySelector('#account-button').click();assert.equal(d.querySelector('a[href="/service.html?view=admin"]'),null);const offline=await page(t,'offline');assert.equal(offline.querySelector('#account-button').textContent,'登录');assert.ok(offline.querySelector('a[href="/workspace.html#home"]'));});
