import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mountNavigation,trackDialogForm} from '../dist/workspace/interface.mjs';
import {formatDate} from '../dist/workspace/ui.mjs';
function setup(){const dom=new JSDOM('<aside id="nav"><a href="#home">首页</a><button>账户</button></aside><button id="toggle">菜单</button><button id="backdrop"></button><main><input></main><dialog><form><input id="name" value=""><select id="degree"><option>本科</option><option>硕士</option></select></form></dialog>',{url:'http://localhost/'});globalThis.window=dom.window;globalThis.document=dom.window.document;return dom;}
test('closed mobile navigation is inert, open navigation traps focus and Escape restores toggle',()=>{const dom=setup();let changed;const media={matches:true,addEventListener:(_,f)=>changed=f,removeEventListener:()=>{}};const sidebar=document.querySelector('aside'),toggle=document.querySelector('#toggle'),main=document.querySelector('main');const nav=mountNavigation({sidebar,toggle,main,backdrop:document.querySelector('#backdrop'),media});assert.equal(sidebar.inert,true);assert.equal(toggle.getAttribute('aria-expanded'),'false');assert.equal(toggle.getAttribute('aria-controls'),'nav');toggle.click();assert.equal(main.inert,true);assert.equal(document.activeElement.textContent,'首页');document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));assert.equal(document.activeElement.textContent,'账户');document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(sidebar.inert,true);assert.equal(main.inert,false);assert.equal(document.activeElement,toggle);media.matches=false;changed();assert.equal(sidebar.inert,false);nav.dispose();dom.window.close();});
test('crossing to mobile while sidebar focused does not leave invisible focus',()=>{const dom=setup();let changed;const media={matches:false,addEventListener:(_,f)=>changed=f,removeEventListener:()=>{}};const sidebar=document.querySelector('aside'),toggle=document.querySelector('#toggle');const nav=mountNavigation({sidebar,toggle,main:document.querySelector('main'),media});sidebar.querySelector('a').focus();media.matches=true;changed();assert.equal(document.activeElement,toggle);assert.equal(sidebar.inert,true);nav.dispose();dom.window.close();});
test('dirty dialog close preserves input until explicit discard, repeated close creates one prompt',()=>{const dom=setup();const dialog=document.querySelector('dialog');let closes=0;dialog.close=()=>closes++;const close=trackDialogForm(dialog);document.querySelector('#name').value='未保存项目';close();close();assert.equal(closes,0);assert.equal(dialog.querySelectorAll('.dialog-leave-confirm').length,1);dialog.querySelector('.dialog-leave-confirm button').click();assert.equal(dialog.querySelector('.dialog-leave-confirm'),null);assert.equal(document.querySelector('#name').value,'未保存项目');close();dialog.querySelectorAll('.dialog-leave-confirm button')[1].click();assert.equal(closes,1);dom.window.close();});
test('unchanged or reverted dialog closes without confirmation; select changes are protected',()=>{const dom=setup();const dialog=document.querySelector('dialog');let closes=0;dialog.close=()=>closes++;const close=trackDialogForm(dialog);close();assert.equal(closes,1);document.querySelector('#degree').value='硕士';close();assert.equal(closes,1);dialog.querySelector('.dialog-leave-confirm button').click();document.querySelector('#degree').value='本科';close();assert.equal(closes,2);dom.window.close();});
test('timestamps use Shanghai time, and unknown dates never expose raw invalid strings',()=>{assert.equal(formatDate('2026-10-04T18:22:56.092Z'),'10/05 02:22');assert.equal(formatDate('2026/10/4 23:02:30'),'10/04 23:02');assert.equal(formatDate('本地保存'),'时间未记录');assert.equal(formatDate(undefined),'时间未记录');});
function desktopSetup(){const dom=setup();const sidebar=document.querySelector('aside');sidebar.insertAdjacentHTML('beforeend','<button id="collapse">收起</button><div id="resize" tabindex="0"></div>');let change;const media={matches:false,addEventListener:(_,f)=>change=f,removeEventListener:()=>{}};const args={sidebar,toggle:document.querySelector('#toggle'),main:document.querySelector('main'),media,desktop:{root:document.body,handle:document.querySelector('#resize'),collapse:document.querySelector('#collapse')}};return {dom,args,change:()=>change()};}
test('desktop collapse releases content space, protects hidden focus and persists across remount',()=>{const {dom,args}=desktopSetup();let nav=mountNavigation(args);args.sidebar.querySelector('a').focus();args.desktop.collapse.click();assert.equal(document.body.classList.contains('navigation-hidden'),true);assert.equal(args.sidebar.inert,true);assert.equal(document.activeElement,args.toggle);assert.equal(args.toggle.getAttribute('aria-label'),'展开菜单');nav.dispose();nav=mountNavigation(args);assert.equal(args.sidebar.inert,true);args.toggle.click();assert.equal(args.sidebar.inert,false);assert.equal(args.toggle.getAttribute('aria-expanded'),'true');assert.equal(JSON.parse(window.localStorage.getItem('paperknow.navigation')).collapsed,false);nav.dispose();dom.window.close();});
test('pointer drag and keyboard resizing are bounded, stored and resettable',()=>{const {dom,args}=desktopSetup();const nav=mountNavigation(args),handle=args.desktop.handle;const pointer=(type,x)=>handle.dispatchEvent(new window.MouseEvent(type,{clientX:x,button:0,bubbles:true,cancelable:true}));pointer('pointerdown',256);pointer('pointermove',900);pointer('pointerup',900);assert.equal(handle.getAttribute('aria-valuenow'),'360');assert.equal(JSON.parse(window.localStorage.getItem('paperknow.navigation')).width,360);handle.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Home',bubbles:true,cancelable:true}));assert.equal(handle.getAttribute('aria-valuenow'),'240');handle.dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(handle.getAttribute('aria-valuenow'),'256');handle.dispatchEvent(new window.MouseEvent('dblclick',{bubbles:true}));assert.equal(document.body.style.getPropertyValue('--navigation-width'),'256px');nav.dispose();dom.window.close();});
test('desktop hidden preference does not prevent mobile opening and closing',()=>{const {dom,args,change}=desktopSetup();window.localStorage.setItem('paperknow.navigation',JSON.stringify({collapsed:true,width:320}));const nav=mountNavigation(args);args.media.matches=true;change();args.toggle.click();assert.equal(args.sidebar.inert,false);assert.equal(args.main.inert,true);args.desktop.collapse.click();assert.equal(args.sidebar.inert,true);assert.equal(args.main.inert,false);args.media.matches=false;change();assert.equal(args.sidebar.inert,true);assert.equal(args.toggle.getAttribute('aria-label'),'展开菜单');nav.dispose();dom.window.close();});
