import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../dist/service.html',import.meta.url),'utf8');
const code=await readFile(new URL('../dist/service.mjs',import.meta.url),'utf8');
async function settle(check){for(let i=0;i<60;i++){if(check())return;await new Promise(r=>setTimeout(r,5));}throw new Error('UI did not settle');}
async function ui(t,{ai=false,url='http://localhost/service.html',role='user',guest=false}={}){const dom=new JSDOM(html,{url,runScripts:'outside-only'});const w=dom.window;t.after(()=>w.close());w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};let saved=[],jobs=[];w.fetch=async(path,options={})=>{const b=options.body?JSON.parse(options.body):null;let value;if(path==='/api/capabilities')value={ai,aiProvider:'test.invalid'};else if(path==='/api/auth/me'&&guest)return {ok:false,status:401,json:async()=>({error:'未登录'})};else if(path==='/api/auth/me')value={user:{id:'test',name:'UI 测试',email:'test@example.invalid',role}};else if(path==='/api/jobs'){if(b){jobs.push({id:'job',type:b.type,status:'completed',attempt:1,result_id:'result',created_at:new Date().toISOString()});value={id:'job'};}else value={items:jobs};}else if(path==='/api/results')value={items:[{id:'result',type:'polish',title:'测试桩建议',created_at:new Date().toISOString()}]};else if(path==='/api/results/result')value={item:{id:'result',type:'polish',title:'测试桩建议',body:{original:'原文',suggestion:'原始建议',model:'test-fixture'}}};else if(path==='/api/results/result/revisions'){if(b){saved.unshift({id:'version',body:b.text,created_at:new Date().toISOString()});value={id:'version'};}else value={items:saved};}else value={items:[]};return {ok:true,status:200,json:async()=>value};};w.eval('(async()=>{'+code+'})()');await settle(()=>w.document.querySelector(guest?'#auth-form':'[data-view="tasks"]')); return {w,doc:w.document,saved};}
function click(doc,selector){doc.querySelector(selector).click();}
function input(w,selector,value){const el=w.document.querySelector(selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
function submit(w,formId,button){w.document.querySelector(formId).dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:button}));}
test('service form navigation preserves modified input until explicit discard, and Escape declines',async t=>{const {w,doc}=await ui(t);click(doc,'[data-view="tasks"]');await settle(()=>doc.querySelector('#task-form'));await new Promise(r=>setTimeout(r,5));input(w,'#task-text','待保存正文');click(doc,'[data-view="projects"]');assert.equal(doc.querySelector('#service-confirm').open,true);click(doc,'#confirm-no');assert.equal(doc.querySelector('#task-text').value,'待保存正文');assert.equal(doc.querySelector('#service-confirm').open,false);click(doc,'[data-view="projects"]');doc.querySelector('#service-confirm').dispatchEvent(new w.Event('cancel',{cancelable:true}));assert.equal(doc.querySelector('#task-text').value,'待保存正文');click(doc,'[data-view="projects"]');click(doc,'#confirm-yes');await settle(()=>doc.querySelector('#project-form'));assert.equal(doc.querySelector('#task-form'),null);});
test('completed material task reset cannot enable unavailable AI submit button',async t=>{const {w,doc}=await ui(t);click(doc,'[data-view="tasks"]');await settle(()=>doc.querySelector('#task-form'));const select=doc.querySelector('#task-type');select.value='compare';select.dispatchEvent(new w.Event('change'));input(w,'#task-text','实际原文');input(w,'#source-title','实际来源');input(w,'#source-text','实际正文');submit(w,'#task-form',doc.querySelector('#task-submit'));await settle(()=>doc.querySelector('#task-type').value==='polish');assert.equal(doc.querySelector('#task-submit').disabled,true);assert.equal(doc.querySelector('#task-text').maxLength,6000);assert.equal(doc.querySelector('#task-text').value,'');});
test('opening saved suggestions is clean, explicit edit save preserves a new version',async t=>{const {w,doc,saved}=await ui(t,{ai:true});click(doc,'[data-view="results"]');await settle(()=>doc.querySelector('[data-result]'));click(doc,'[data-result]');await settle(()=>doc.querySelector('#revision-form'));await new Promise(r=>setTimeout(r,5));assert.equal(doc.querySelector('#revision-text').value,'原始建议');click(doc,'[data-view="home"]');await settle(()=>doc.querySelector('#job-list'));assert.equal(doc.querySelector('#service-confirm').open,false);click(doc,'[data-result]');await settle(()=>doc.querySelector('#revision-form'));input(w,'#revision-text','人工编辑稿');submit(w,'#revision-form',doc.querySelector('#revision-form button'));await settle(()=>saved.length===1);await settle(()=>doc.querySelector('#notice').textContent==='新版本已保存');await settle(()=>doc.querySelector('#revision-text')?.value==='人工编辑稿');assert.equal(doc.querySelector('#service-confirm').open,false);assert.equal(saved[0].body,'人工编辑稿');});

test('registration entry opens registration and project deep link survives login state',async t=>{const {doc}=await ui(t,{guest:true,url:'http://localhost/service.html?auth=register&view=projects'});assert.ok(doc.querySelector('#name'));assert.equal(doc.querySelector('h1').textContent,'创建服务账户');const signed=await ui(t,{url:'http://localhost/service.html?view=projects'});assert.ok(signed.doc.querySelector('#project-form'));});
test('admin deep link honors actual account role',async t=>{const regular=await ui(t,{url:'http://localhost/service.html?view=admin'});assert.ok(regular.doc.querySelector('#job-list'));assert.equal(regular.doc.querySelector('[data-view="admin"]'),null);const admin=await ui(t,{role:'admin',url:'http://localhost/service.html?view=admin'});assert.equal(admin.doc.querySelector('[data-view="admin"]').getAttribute('aria-pressed'),'true');});
