import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {validateBackup,planMerge} from '../dist/workspace/backup-model.mjs';
import {currentBackup,restoreBackup,fingerprint,storageKeys} from '../dist/workspace/backup-service.mjs';
import {normalizeSettings} from '../dist/workspace/settings-model.mjs';
import {repository} from '../dist/precheck/store.mjs';
import {analyzeDocument,parseDocument} from '../dist/precheck/engine.mjs';
const raw=(data={})=>({format:'paperknow-workspace-backup',version:1,...data});
const text='科研工作需要以真实数据和有效引用为基础进行分析与讨论';
const report=()=>analyzeDocument(parseDocument(text),[{id:'settings-source',title:'自建测试材料',authors:[],text,provider:'user',kind:'user'}]);
class MemoryStorage{map=new Map();getItem(k){return this.map.get(k)??null;}setItem(k,v){if(this.fail===k){this.fail=null;throw Error('quota');}this.map.set(k,v);}removeItem(k){this.map.delete(k);}}
test('backup validates complete deterministic report, rejects broken ranges and unsafe URLs',()=>{const r=report();assert.equal(validateBackup(raw({reports:[r]})).reports[0].ratio,1);const broken=structuredClone(r);broken.sections[0].paragraphs[0].matches[0].range=[0,9999];assert.throws(()=>validateBackup(raw({reports:[broken]})),/区间/);r.sources[0].url='javascript:alert(1)';assert.throws(()=>validateBackup(raw({reports:[r]})),/HTTP/);});
test('backup rejects unknown versions, duplicate IDs and prototype keys; strips active draft markup',()=>{assert.throws(()=>validateBackup(raw({version:2})));assert.throws(()=>validateBackup(raw({projects:[{id:'p',name:'a'},{id:'p',name:'b'}]})));assert.throws(()=>validateBackup(JSON.parse('{"format":"paperknow-workspace-backup","version":1,"__proto__":{}}')));const d=validateBackup(raw({drafts:[{id:'d',title:'a',tool:'writing',html:'<p onclick="x()">正文<img src="https://test.invalid"></p>'}]})).drafts[0];assert.equal(d.html,'正文</p>');});
test('merge preserves current edits and reports orphaned associations',()=>{const current={projects:[{id:'p',name:'新版'}],drafts:[],reports:[],literature:[],tasks:[]};const incoming=validateBackup(raw({projects:[{id:'p',name:'旧版'}],drafts:[{id:'d',tool:'writing',title:'草稿',projectId:'missing'}]}));const plan=planMerge(current,incoming);assert.equal(plan.merged.projects[0].name,'新版');assert.equal(plan.summary[0].skipped,1);assert.equal(plan.orphaned,1);});
test('restore adds once, retains settings by default and rolls back local writes and reports on quota failure',async()=>{const storage=new MemoryStorage();storage.setItem(storageKeys.preferences,JSON.stringify({fontSize:'large',projectView:'list'}));const before=await currentBackup(storage);const incoming=validateBackup(raw({projects:[{id:'backup-project-test',name:'测试项目'}],reports:[report()],preferences:{fontSize:'larger'}}));storage.fail=storageKeys.drafts;await assert.rejects(restoreBackup(incoming,fingerprint(before),{storage}),/quota/);assert.deepEqual(await currentBackup(storage),before);await restoreBackup(incoming,fingerprint(before),{storage});const saved=await currentBackup(storage);assert.equal(saved.projects.length,1);assert.equal(saved.preferences.fontSize,'large');assert.equal(saved.reports.length,before.reports.length+1);const summary=await restoreBackup(incoming,fingerprint(saved),{storage});assert.equal(summary.reduce((n,r)=>n+r.added,0),0);await assert.rejects(restoreBackup(incoming,fingerprint(before),{storage}),/已变化/);await repository.remove('reports',incoming.reports[0].id);});
test('personal preferences restore is opt-in and uses whitelisted values',async()=>{const storage=new MemoryStorage();storage.setItem(storageKeys.preferences,JSON.stringify({projectView:'list'}));const before=await currentBackup(storage);await restoreBackup(validateBackup(raw({preferences:{density:'compact',fontSize:'larger',unknown:'discard'}})),fingerprint(before),{storage,restorePersonal:true});const saved=(await currentBackup(storage)).preferences;assert.equal(saved.projectView,'list');assert.equal(saved.fontSize,'larger');assert.equal(saved.unknown,undefined);assert.deepEqual(normalizeSettings({fontSize:'bad',degree:'bad'}),{degree:'本科',major:'',density:'comfortable',fontSize:'normal'});});
test('report transaction abort also restores local snapshots after local writes succeeded',async()=>{const storage=new MemoryStorage();const before=await currentBackup(storage),r=report();const incoming=validateBackup(raw({projects:[{id:'abort-project',name:'回滚测试'}],reports:[r]}));incoming.reports.push(structuredClone(r));await assert.rejects(restoreBackup(incoming,fingerprint(before),{storage}));assert.deepEqual(await currentBackup(storage),before);});
