import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {catalog} from '../dist/workspace/writing-catalog.mjs';
function setup(){const dom=new JSDOM('<aside class="sidebar"></aside><div class="breadcrumb"><strong></strong></div><main class="dashboard"></main><dialog id="workspace-dialog"><div id="workspace-dialog-body"></div></dialog>',{url:'http://localhost/workspace.html#category/writing'});for(const k of ['window','document','localStorage','FormData','location','AbortController'])globalThis[k]=dom.window[k];dom.window.HTMLElement.prototype.scrollIntoView=()=>{};document.querySelector('dialog').close=()=>{};return {dom,ctx:{notify:()=>{},modal:(_,html)=>document.querySelector('#workspace-dialog-body').innerHTML=html}};}
setup();
const {mountWriting}=await import('../dist/workspace/writing.mjs');
const {mountWritingSupport,supportFields}=await import('../dist/workspace/writing-support.mjs');
const {clearEditor,editorHasWork}=await import('../dist/workspace/edit-guard.mjs');
const $=s=>document.querySelector(s);
function input(s,v){$(s).value=v;$(s).dispatchEvent(new window.Event('input',{bubbles:true}));}
test('five-step writing confirms material before outline and preserves language, chapters and legacy metadata',()=>{const {dom,ctx}=setup();mountWriting(undefined,undefined,ctx);input('#writing-title','真实研究流程');input('#writing-language','英文');input('#writing-material','真实参考正文');$('#writing-generate').click();assert.equal($('#writing-material-review').hidden,false);assert.equal($('#outline-confirm').disabled,true);$('#writing-material-confirm').click();assert.equal($('[data-writing-step="3"]').getAttribute('aria-current'),'step');assert.match($('#outline-paper').textContent,/写作语言：英文/);$('#outline-confirm').click();input('#body-editor','根据真实研究手动填写的正文。');$('#body-finish').click();assert.equal($('#writing-export-area').hidden,false);assert.match($('#body-preview').textContent,/根据真实研究/);$('#writing-save').click();let saved=JSON.parse(localStorage.getItem('paperknow-drafts'))[0];saved.legacyMetadata='保留旧字段';localStorage.setItem('paperknow-drafts',JSON.stringify([saved]));clearEditor();mountWriting(saved.id,undefined,ctx);assert.equal($('#body-editor').value,'根据真实研究手动填写的正文。');assert.equal($('#writing-language').value,'英文');$('#writing-save').click();assert.equal(JSON.parse(localStorage.getItem('paperknow-drafts'))[0].legacyMetadata,'保留旧字段');clearEditor();dom.window.close();});
test('guide preference persists across task changes without marking the editor dirty and limitations stay visible',()=>{const {dom,ctx}=setup();mountWriting(undefined,undefined,ctx);assert.equal($('.writing-catalog').querySelectorAll('a').length,11);assert.equal(catalog.length,11);$('.guide-toggle').click();assert.equal($('#writing-guide').hidden,true);assert.equal(editorHasWork(),false);clearEditor();mountWritingSupport('analysis',undefined,undefined,ctx);assert.equal($('#writing-guide').hidden,true);assert.equal($('.guide-toggle').getAttribute('aria-expanded'),'false');assert.match($('.support-boundary').textContent,/不执行统计运算/);assert.equal($('.support-boundary').hidden,false);$('.guide-toggle').click();assert.equal($('#writing-guide').hidden,false);clearEditor();dom.window.close();});
for(const kind of Object.keys(supportFields))test(`${kind} manual fields and edited output survive save and reopen`,()=>{const {dom,ctx}=setup();mountWritingSupport(kind,undefined,undefined,ctx);input('#support-title','真实任务测试');for(const [key,,type] of supportFields[kind])input('#support-'+key,type==='date'?(key==='start'?'2026-09-01':'2026-09-30'):'用户提供的真实材料');$('#support-form').requestSubmit();assert.match($('#support-output').value,/用户提供的真实材料/);input('#support-output','手动编辑后保留的最终内容');$('#support-save').click();const saved=JSON.parse(localStorage.getItem('paperknow-drafts'))[0];assert.equal(saved.tool,kind);clearEditor();mountWritingSupport(kind,saved.id,undefined,ctx);assert.equal($('#support-output').value,'手动编辑后保留的最终内容');assert.equal($('#support-'+supportFields[kind][0][0]).value,'用户提供的真实材料');$('#support-form').requestSubmit();assert.equal($('#support-output').value,'手动编辑后保留的最终内容');assert.ok($('#support-replace'));clearEditor();dom.window.close();});
test('practice rejects reversed dates for both framework creation and save',()=>{const {dom,ctx}=setup();mountWritingSupport('practice',undefined,undefined,ctx);input('#support-title','真实实践报告');input('#support-start','2026-09-30');input('#support-end','2026-09-01');$('#support-form').requestSubmit();assert.equal($('#support-output').value,'');assert.match($('#support-error').textContent,/不能早于/);$('#support-save').click();assert.equal(localStorage.getItem('paperknow-drafts'),null);clearEditor();dom.window.close();});
